Updated build scripts.

diff --git a/ci/test b/ci/test
--- a/ci/test
+++ b/ci/test
@@ -19,23 +19,28 @@
 # Contact: dreibh@iem.uni-due.de
 
 
+CONTAINER="ubuntu-test"
+
+
 # ###### Linux ##############################################################
-if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
+if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
 
    # ====== pbuilder environment ============================================
    if [ "$TOOL" == "pbuilder" ] ; then
       CHANGELOG_HEADER="`head -n1 debian/changelog`"
       PACKAGE=`echo ${CHANGELOG_HEADER} | sed -e "s/(.*//" -e "s/ //g"`
       PACKAGE_VERSION=`echo ${CHANGELOG_HEADER} | sed -e "s/.*(//" -e "s/).*//" -e "s/ //g" -e "s/ //g" -e "s/^[0-9]://g"`
+      OUTPUT_VERSION=`echo ${PACKAGE_VERSION}   | sed -e "s/\(ubuntu\|ppa\)[0-9]*$/\1/"`
+      DEBIAN_VERSION=`echo ${OUTPUT_VERSION}    | sed -e "s/\(ubuntu\|ppa\)$//1"`
 
       packages=""
       if [ $#  -eq 0 ] ; then
-         echo "Looking for ${PACKAGE}*${PACKAGE_VERSION}*.deb in /var/cache/pbuilder/result ..."
-         packages="`sudo docker exec ubuntu-test env LANG=C.UTF-8 find /var/cache/pbuilder/result -name "${PACKAGE}*${PACKAGE_VERSION}*.deb"`"
+         echo "Looking for *${DEBIAN_VERSION}*.deb in /var/cache/pbuilder/result ..."
+         packages="`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 find /var/cache/pbuilder/result -name "*${DEBIAN_VERSION}*.deb"`"
       fi
       while [ $# -gt 0 ] ; do
-         echo "Looking for $1*${PACKAGE_VERSION}*.deb in /var/cache/pbuilder/result ..."
-         packages="${packages} `sudo docker exec ubuntu-test env LANG=C.UTF-8 find /var/cache/pbuilder/result -name "$1*${PACKAGE_VERSION}*.deb"`"
+         echo "Looking for $1*${DEBIAN_VERSION}*.deb in /var/cache/pbuilder/result ..."
+         packages="${packages} `sudo docker exec ${CONTAINER} env LANG=C.UTF-8 find /var/cache/pbuilder/result -name "$1*${DEBIAN_VERSION}*.deb"`"
          shift
       done
       packages=`echo "${packages}" | xargs -n1 | sort -u | xargs`
@@ -45,7 +50,13 @@ if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       fi
 
       echo "Installing ${packages} ..."
-      sudo docker exec ubuntu-test env LANG=C.UTF-8 apt-get install -y --allow-downgrades ${packages}
+      # NOTE: Older "apt-get" versions do not handle local files!
+      if ! sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive dpkg -i ${packages} ; then
+         echo "There may be some dependencies missing. Trying to install them ..."
+         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive apt-get install -fy -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" --no-install-recommends
+         echo "Retrying to install ${packages} ..."
+         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive dpkg -i ${packages}
+      fi
       echo "Done!"
 
    # ====== mock environment ================================================
@@ -53,10 +64,10 @@ if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       PACKAGE=`grep "^Name:" rpm/*.spec | head -n1 | sed -e "s/Name://g" -e "s/[ \t]*//g"`
       PACKAGE_VERSION=`grep "^Version:" rpm/*.spec | head -n1 | sed -e "s/Version://g" -e "s/[ \t]*//g"`
 
-      release=`sudo docker exec -t ubuntu-test bash -c "LANG=C.UTF-8 ; cat /etc/fedora-release | sed -e \"s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g\"" | sed -e "s/[^0-9]//g"`
-      arch=`sudo docker exec -t ubuntu-test env LANG=C.UTF-8 uname -m | sed -e "s/[^0-9a-zA-Z_-+]//g"`
-      if ! sudo docker exec -t ubuntu-test cd /var/lib/mock/fedora-${release}-${arch}/result ; then
-         if sudo docker exec -t ubuntu-test cd /var/lib/mock/fedora-rawhide-${arch}/result ; then
+      release=`sudo docker exec ${CONTAINER} bash -c "LANG=C.UTF-8 ; cat /etc/fedora-release | sed -e \"s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g\"" | sed -e "s/[^0-9]//g"`
+      arch=`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 uname -m | sed -e "s/[^0-9a-zA-Z_-+]//g"`
+      if ! sudo docker exec ${CONTAINER} cd /var/lib/mock/fedora-${release}-${arch}/result ; then
+         if sudo docker exec ${CONTAINER} cd /var/lib/mock/fedora-rawhide-${arch}/result ; then
             release="rawhide"
          else
             echo >&2 "ERROR: No results have been found!"
@@ -66,12 +77,12 @@ if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
 
       packages=""
       if [ $#  -eq 0 ] ; then
-         echo "Looking for ${PACKAGE}*${PACKAGE_VERSION}*.rpm in /var/lib/mock/fedora-${release}-${arch}/result ..."
-         packages="`sudo docker exec ubuntu-test env LANG=C.UTF-8 find /var/lib/mock/fedora-${release}-${arch}/result -name "${PACKAGE}*${PACKAGE_VERSION}*.rpm" | grep -v "\.src\.rpm$"`"
+         echo "Looking for *${PACKAGE_VERSION}*.rpm in /var/lib/mock/fedora-${release}-${arch}/result ..."
+         packages="`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 find /var/lib/mock/fedora-${release}-${arch}/result -name "*${PACKAGE_VERSION}*.rpm" | grep -v "\.src\.rpm$"`"
       fi
       while [ $# -gt 0 ] ; do
          echo "Looking for $1*${PACKAGE_VERSION}*.rpm in /var/lib/mock/fedora-${release}-${arch}/result ..."
-         packages="${packages} `sudo docker exec ubuntu-test env LANG=C.UTF-8 find /var/lib/mock/fedora-${release}-${arch}/result -name "$1*${PACKAGE_VERSION}*.rpm" | grep -v "\.src\.rpm$"`"
+         packages="${packages} `sudo docker exec ${CONTAINER} env LANG=C.UTF-8 find /var/lib/mock/fedora-${release}-${arch}/result -name "$1*${PACKAGE_VERSION}*.rpm" | grep -v "\.src\.rpm$"`"
          shift
       done
       packages=`echo "${packages}" | xargs -n1 | sort -u | xargs`
@@ -81,7 +92,7 @@ if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       fi
 
       echo "Installing ${packages} ..."
-      sudo docker exec ubuntu-test env LANG=C.UTF-8 dnf install -y --allowerasing ${packages}
+      sudo docker exec ${CONTAINER} env LANG=C.UTF-8 dnf install -y --allowerasing ${packages}
       echo "Done!"
 
    fi
